spring:
  application:
    name: client
server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8700/eureka/
feign:
  circuitbreaker:
    enabled: true
  okhttp:
    enabled: true