spring:
  application:
    name: service-test
server:
  port: 8801
eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8700/eureka/